#  ____   _   _   ____   _____   _____   ___  ___   ____   ____
# |  __| | | | | | ___| |_   _| |  _  | |   \/   | | ___| | __ \
# | |__  | |_| | |___ |   | |   | |_| | | |\  /| | | __|  |   _/
# |____| |_____| |____|   |_|   |_____| |_| \/ |_| |____| |_|\_\
#
### specific customer
DELETE http://localhost:3000/api/v1/customer

{ "id": 25 }



#  ____   ____   _____   ____    _   _   ____   _____
# | __ \ | __ \ |  _  | |    \  | | | | |  __| |_   _|
# |  __/ |   _/ | |_| | | |)  | | |_| | | |__    | |
# |_|    |_|\_\ |_____| |____/  |_____| |____|   |_|
#
### specific seller, all products
DELETE http://localhost:3000/api/v1/product

{ "seller_id": 1 }

### specific seller, specific product
DELETE http://localhost:3000/api/v1/product

{ "id": 9, "seller_id": 1 }



#  ____    ___    ____   _____
# |  __|  / _ \  | __ \ |_   _|
# | |__  |  _  | |   _/   | |
# |____| |_| |_| |_|\_\   |_|
#
### specific customer, all carts
DELETE http://localhost:3000/api/v1/cart

{ "customer_id": 1 }

### specific customer, specific cart
DELETE http://localhost:3000/api/v1/cart

{ "id": 1, "customer_id": 1 }
